### ISSUE TITLE
Is a panic expected?

### ISSUE THREAD

**Issue by AndrejMitrovic** [bobg/scp#8]
I'm not sure if the code handles the case when there is a misconfiguration of the quorums.

I have some test code which generates random quorum configurations. I've fed that to the `lunch` script, but I get a consensus failure for the very first slot:

```
panic: consensus failure

goroutine 9 [running]:
github.com/bobg/scp.(*Node).handle(0xc0001c8e40, 0xc0000adae0, 0x64dce0, 0x54e03f4)
        /mnt/c/dev/go/src/github.com/bobg/scp/node.go:168 +0x2df
github.com/bobg/scp.(*Node).Run.func1(0xc000607f88, 0xc0001c8e40, 0xc0003aa258)
        /mnt/c/dev/go/src/github.com/bobg/scp/node.go:89 +0x64
github.com/bobg/scp.(*Node).Run(0xc0001c8e40, 0x57a060, 0xc0000120d0)
        /mnt/c/dev/go/src/github.com/bobg/scp/node.go:93 +0x222
created by main.main
        /mnt/c/dev/go/go-scp/cmd/lunch/lunch.go:82 +0x3e1
exit status 2
```

I'm wondering if this is expected [if the configuration is bad], or if the code needs fixing somewhere.

Here's the example .toml file I've used it with: https://gist.github.com/AndrejMitrovic/0c96bccf7fa3f135a0cf34af851e279c

**Comment by AndrejMitrovic** [comment]
I've now realized that my quorum fails with the `isQuorumSetSane` check in scp-core. So this is likely not an issue with your project. :)

I'll close the issue.
